name: Release Igloo CLI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/release-igloo-cli.yaml"
      - "apps/igloo-cli-npm/**"
      - "apps/igloo-kit-cli/**"
      - "apps/create-igloo-app/**"
      - "packages/**"

jobs:
  version:
    concurrency: release
    if: ${{ ! contains(github.event.head_commit.message , '[no-release]') }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Generate Version
        id: version
        run: |
          ./scripts/version.js ${{ github.sha }} >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.version.outputs.VERSION }}
          generateReleaseNotes: true
          commit: ${{ github.sha }}

  build-and-publish-binaries:
    name: Build CLI Binaries
    runs-on: ${{ matrix.build.os }}
    needs: version
    outputs:
      version: ${{ steps.version.outputs.version }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - {
              NAME: linux-x64-glibc,
              OS: ubuntu-20.04,
              TOOLCHAIN: stable,
              TARGET: x86_64-unknown-linux-gnu,
            }
          - {
              NAME: linux-arm64-glibc,
              OS: ubuntu-20.04,
              TOOLCHAIN: stable,
              TARGET: aarch64-unknown-linux-gnu,
            }
          - {
              NAME: darwin-x64,
              OS: macos-11,
              TOOLCHAIN: stable,
              TARGET: x86_64-apple-darwin,
            }
          - {
              NAME: darwin-arm64,
              OS: macos-11,
              TOOLCHAIN: stable,
              TARGET: aarch64-apple-darwin,
            }
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.build.TOOLCHAIN }}
          target: ${{ matrix.build.TARGET }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Install Set Version
        run: |
          cargo install cargo-edit
          cargo set-version ${{ needs.version.outputs.version }}
        working-directory: ./apps/igloo-kit-cli

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./apps/igloo-kit-cli/Cargo.toml --release --locked --target ${{ matrix.build.TARGET }}
          use-cross: ${{ matrix.build.OS == 'ubuntu-20.04' }} # use `cross` for Linux builds

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Publish to NPM
        shell: bash
        working-directory: ./apps/igloo-cli-npm
        run: ./scripts/release-bin.sh ${{ needs.version.outputs.version }} ${{ matrix.build.TARGET }} ${{ matrix.build.OS }} ${{ matrix.build.NAME }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload binary
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ needs.version.outputs.version }}
          allowUpdates: "true"
          replacesArtifacts: "false"
          artifacts: |
            ./apps/igloo-kit-cli/target/${{ matrix.build.TARGET }}/release/igloo-cli-${{ matrix.build.TARGET }}

  publish-npm-base:
    name: Publish the base NPM package
    needs:
      - version
      - build-and-publish-binaries
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Login GSAP
        shell: bash
        run: |
          pnpm config set //npm.greensock.com/:_authToken ${{ secrets.GSAP_TOKEN }}
          pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          cd ./apps/web
          pnpm install gsap@npm:@gsap/business

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Publish the NPM CLI package
        shell: bash
        run: ./apps/igloo-cli-npm/scripts/release-cli.sh ${{ needs.version.outputs.version }}

      - name: Publish the NPM create app package
        shell: bash
        run: ./apps/create-igloo-app/scripts/release.sh ${{ needs.version.outputs.version }}

      - name: Notify Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_IGLOO_CLI_PROJECT }}
        with:
          environment: production
          version: ${{ needs.version.outputs.version }}
